version: "3"
services:
  mongodb:
    image: mongo:4.4.6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongodb
    build: ./
    restart: always
    env_file: ./.env
    ports:
      - 8081:8081
    environment:
      - DB_HOST=mongodb
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=27017
volumes:
  db:
