version: "3.7"
services:
  mongodb:
    container_name: container-mongodb
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: password
    #   MONGO_INITDB_DATABASE: root-db
    # volumes:
    #   - db_store:/data/db
  app:
    depends_on:
      - mongodb
    build: ./
    restart: always
    env_file: ./.env
    ports:
      - 8081:8081
volumes:
  db_store:
